language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - '4'
  - '6'
before_install:
  - npm install -g npm@3
before_script:
  - npm prune
script:
  - ./next-update-travis.sh
  - npm test
after_success:
  - ["`node -v`" == v6*] && npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
